# application.yml

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시 데이터베이스 테이블을 새로 생성 (기존 데이터가 모두 삭제)
    properties:
      hibernate:
       #show_sql: true # system.out을 통해 출력
        format_sql: true # Hibernate가 생성하는 SQL을 보기 좋게 정렬 (Pretty Print)

logging:
  level:
    org.hibernate.SQL: debug # log를 통해 출력
    org.hibernate.type: trace